# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Murillo
tagline:          'Murillo Fernando Rodrigues - Welcome to my personal webpage/blog!'
description:      'evolutionary biologist & data science enthusiast'
url:              mufernando.github.io
baseurl:          /

author:
  name: 'Murillo Fernando Rodrigues'
  email: 'murillofer.rodrigues@gmail.com'
  github: mufernando
  disqus_shortname: mufernando
  bio: M.Sc. student at University of Sao Paulo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mufernando
