# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Murillo
tagline:          'biologist'
description:      'M. F. Rodrigues — biologist & aspiring data scientist'
url:              mufernando.github.io
baseurl:          /

author:
  name: 'Murillo Fernando Rodrigues'
  email: 'aulas[dot]ludus[at]gmail[dot]com[dot]'
  github: mufernando
  disqus_shortname: mufernando
  bio: M.Sc. student at University of Sao Paulo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mufernando
